function skillsMember() {
    var skills = [
        "HTML",
        "CSS",
        "JavaScript",
        "React",
        "Node.js",
        "MongoDB",
        "Express",
        "Docker",
        "Kubernetes",
        "Git",
        "Jenkins",
        "Jest",
        "Cypress",
        "Webpack",
        "Babel",
        "Python",
        "Ruby",
        "Java",
        "C",
        "C++",
        "C#",
        "PHP",
        "Go",
        "Swift",
        "Kotlin",
        "Objective-C",
        "SQL",
        "NoSQL",
        "PostgreSQL",
        "MySQL",
        "SQLite",
        "Redis",
        "GraphQL",
        "Apollo",
        "Prisma",
        "REST API",
        "WebSocket",
        "OAuth",
        "JSON",
        "XML",
        "YAML",
        "Markdown",
        "Linux",
        "MacOS",
        "Windows",
        "AWS",
        "Azure",
        "Google Cloud",
        "Heroku",
        "Netlify",
        "Vercel",
        "Firebase",
        "DigitalOcean",
        "Nginx",
        "Apache",
        "IIS",
        "Django",
        "Flask",
        "Ruby on Rails",
        "Spring",
        "Hibernate",
        "JPA",
        "ASP.NET",
        "Laravel",
        "Vue.js",
        "Angular",
        "Svelte",
        "Ember",
        "Backbone",
        "Redux",
        "MobX",
        "Vuex",
        "RxJS",
        "D3.js",
        "Three.js",
        "TensorFlow",
        "Keras",
        "PyTorch",
        "Scikit-learn",
        "Pandas",
        "NumPy",
        "Matplotlib",
        "Seaborn",
        "Plotly",
        "Bokeh",
        "Jupyter",
        "VS Code",
        "Vim",
        "Sublime Text",
        "Atom",
        "WebStorm",
        "PyCharm",
        "IntelliJ IDEA",
        "Eclipse",
        "NetBeans",
        "Visual Studio",
        "Xcode",
        "Android Studio"
    ];
    return skills;
}
